#!/bin/bash

N=$1
START=0
GAP=$N

make
rm -f add_test.log add_test.stat add_test.tmp

for (( i=0 ; i<100 ; i++)); do
    ./add_test 0 $N $START $GAP | tee add_test.tmp
    cat add_test.tmp >> add_test.log
done
cat add_test.log | grep us | awk '{ print $5}' > add_test.${N}.stat
rm -f add_test.tmp add_test.log
awk '{ total += $1; count++ } END { print total/count }' add_test.${N}.stat 
