#!/bin/bash

START=0
LOOPS=10

function run {
    ./add_test 0 $1 $START $2 $LOOPS | tee add_test.tmp
    grep Average add_test.tmp | awk '{ print $3}' >> add_test.result
}

for (( n=2 ; n<8 ; n++)); do
    N=$((10**n))
    gap=$N
    run $N $gap
    sleep 1
done
