#!/bin/bash

START=0
LOOPS=100

function run {
    ./add_test 0 $1 $START $2 $LOOPS #| grep Average | \
	#awk '{ print $2}' > add_test.${1}.stat
}

for (( n=2 ; n<8 ; n++)); do
    N=$((10**n))
    gap=$N
    run $N $gap
    sleep 1
done
